name: Issue Metrics

on: push

permissions:
  issues: write
  pull-requests: read

env:
  API_TOKEN: ${{ secrets.NEW_API_TOKEN }}

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
      - name: Get issue metrics 202209
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2022-09-01..2022-09-30 assignee:waki-goq"

      - name: Create issue 202209
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2022年9月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202210
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2022-10-01..2022-10-31 assignee:waki-goq"

      - name: Create issue 202210
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2022年10月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202211
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2022-11-01..2022-11-30 assignee:waki-goq"

      - name: Create issue 202211
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2022年11月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202212
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2022-12-01..2022-12-31 assignee:waki-goq"

      - name: Create issue 202212
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2022年12月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202301
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-01-01..2023-01-31 assignee:waki-goq"

      - name: Create issue 202301
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年1月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202302
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-02-01..2023-02-28 assignee:waki-goq"

      - name: Create issue 202302
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年2月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202303
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-03-01..2023-03-31 assignee:waki-goq"

      - name: Create issue 202303
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年3月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202304
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-04-01..2023-04-30 assignee:waki-goq"

      - name: Create issue 202304
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年4月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202305
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-05-01..2023-05-31 assignee:waki-goq"

      - name: Create issue 202305
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年5月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202306
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-06-01..2023-06-30 assignee:waki-goq"

      - name: Create issue 202306
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年6月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202307
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-07-01..2023-07-31 assignee:waki-goq"

      - name: Create issue 202307
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年7月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202308
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-08-01..2023-08-31 assignee:waki-goq"

      - name: Create issue 202308
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年8月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>

      - name: Get issue metrics 202309
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ env.API_TOKEN }}
          SEARCH_QUERY: "repo:GoQSystemInc/GoQSystemOrder is:issue created:2023-09-01..2023-09-30 assignee:waki-goq"

      - name: Create issue 202309
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 2023年9月の全ケース（和木）
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: <YOUR_GITHUB_HANDLE_HERE>
